version: "2"

run:
  go: "1.24"
  concurrency: 4
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    # Essential error checking
    - errcheck      # Check for unchecked errors
    - govet         # Go vet analysis
    - staticcheck   # Advanced Go analyzer
    - unused        # Find unused code

    # Code quality
    - ineffassign   # Detect ineffectual assignments
    - unconvert     # Remove unnecessary type conversions
    - misspell      # Fix spelling mistakes

    # Security
    - gosec         # Security checks

    # Style (less strict)
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code duplication
    - goconst       # Repeated strings that should be constants

linters-settings:
  errcheck:
    check-type-assertions: false  # Too strict for SDK
    check-blank: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 30

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - third_party
  exclude-files:
    - ".*_test\\.go$"
  exclude-rules:
    # Test files - relax most rules
    - linters:
        - dupl
        - errcheck
        - goconst
        - gocyclo
        - gosec
      path: _test\.go

    # Test utilities - relax style rules but keep security checks
    - linters:
        - dupl
        - goconst
        - gocyclo
        - unused
      path: testutil/

    # Example code - relax all rules
    - linters:
        - errcheck
        - gosec
      path: example/

    # Allow blank error assignment in defer (common pattern)
    - linters:
        - errcheck
      text: 'Error return value of .*(Close|Flush|Remove|Write).*is not checked'
      source: 'defer.*\.Close\(\)'
